name: Test and Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code in vm env.
      uses: actions/checkout@v4
    - name: Set up JDK 21 and Maven
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Upload JAR file
      uses: actions/upload-artifact@v4
      with:
        name: jar-files
        path: target
